#+TITLE: OO Software Specification and Construction @@html:<br>@@ (SWE 619 Course Syllabus -  Spring 2022)

#+OPTIONS: ^:nil toc:1

#+HTML_HEAD: <link rel="stylesheet" href="https://nguyenthanhvuh.github.io/files/org.css">
#+HTML_HEAD: <link rel="alternative stylesheet" href="https://nguyenthanhvuh.github.io/files/org-orig.css">

* General Information
  - Instructor: [[https://nguyenthanhvuh.github.io][ThanhVu Nguyen]]
    - Office Hrs: Mondays 2:00PM - 3:00PM (Research Hall 356 and through Zoom link below)
    - Email: [[mailto:tvn@gmu.edu][tvn@gmu.edu]] (Piazza discussion is preferred)
  - TA: Xu Han
    - Email: [[mailto:xhan21@gmu.edu][xhan21@gmu.edu]]
    - Office Hrs: Mondays 3:00PM - 4:00PM (use class Zoom link below)
  - Class:
    - Mondays 4:30PM--7:10PM, Horizon Hall 1012
    - Zoom link for office hrs: https://gmu.zoom.us/j/98393279342 (Passcode: 148674)
    - Piazza: https://piazza.com/gmu/spring2022/swe619nguyen
    - Syllabus and Schedule (this website): [[https://nguyenthanhvuh.github.io/class-oo][https://nguyenthanhvuh.github.io/class-oo]]
    - Assignment Submission (homework, reflection, quizzes, exams): Blackboard (BB)
      
* [[./schedule.org][Schedule and Assignments]]
  
* Syllabus       
** Course Description

   To give the students a solid understanding of modern software construction. To encourage the construction of software systems of high quality. In-depth study of software construction in a modern language including program specifications and OO designs. Concepts such as information hiding, data abstraction, and object-based and object-oriented software construction are discussed and illustrated. This course is part of the core of the SWE program.

   *Prerequisite*: SWE Foundation Courses or equivalent

** Course Materials
   1. Barbara Liskov with John Guttag. [[https://www.amazon.com/Program-Development-Java-Specification-Object-Oriented/dp/0201657686/ref=sr_1_2?dchild=1&qid=1626231221&refinements=p_27%3ABarbara+Liskov&s=books&sr=1-2&text=Barbara+Liskov][/Program Development in Java: Abstraction, Specification, and Object-Oriented Design/]]. Addison Wesley, 2001, ISBN 0-201-65768-6. *Required*. 
     # + [[http://proquest.safaribooksonline.com/book/programming/java/9780768685299][Direct Safari Link]]
     + [[https://learning-oreilly-com.mutex.gmu.edu/library/view/program-development-in/9780768685299/ch1.html][Link]]
       # - Note that you can access the Java 8 APIs at the Oracle site.

   - Joshua Bloch. [[https://www.amazon.com/Effective-Java-Joshua-Bloch/dp/0134685997/ref=sr_1_1?dchild=1&keywords=effective+java&qid=1626231154&sr=8-1][/Effective Java/]]. Third Edition. Addison-Wesley Professional, 2017, ISBN 978-0-13-468599-1. *Required*. 
     # + [[http://proquest.safaribooksonline.com/book/programming/java/9780134686097][Direct Safari Link]]
     + [[https://learning-oreilly-com.mutex.gmu.edu/library/view/effective-java-3rd/9780134686097/cover.xhtml][Link]]
   *Note*: We'll start with Liskov. Don't worry about the publication date; Liskov is basically a math book, and hence ages remarkably well. We're interested in contracts, mutability, data abstraction, and type abstraction. Bloch is concerned about the same things, but explores them in more detail and in more up-to-date Java. Bloch also corrects some important points that weren't well understood when Liskov's text came out.

** Weekly Schedule

   This class is a group-based, /in-person/ offering. You need to be present in class at class time. You will also need to schedule regular meetings with your group.

   Each week will cover a topic, which is a small number of related technical issues (see course [[./schedule.html][schedule]]). Each topic will follow roughly the same sequence of preparation, in-class learning activities, homework completion and (possibly) presentation, and knowledge assessment. Many of these activities will be group based. The sequence is:

   - Preparation: Complete assigned readings and watch relevant videos, if any.  No formal submission for this activity.
   - Reading Reflection: This is a formal opportunity for each group to reflect on the reading.
   - Class Meeting:
     + Combined session on the day's topic, followed by in-class exercises (group breakouts)
     + Break
     + Combined session on the day's topic, may followed by in-class exercises (group breakouts)
   - Homework (group-based)
   - Assessments via quiz: takes place at the *end* of class the same day as the homework is due.

** Grading

   | Assignenmts                        | Percentage |
   |------------------------------------+------------|
   | Group Functioning (group-based)    |         5% |
   | Reading Reflections (group-based)  |        10% |
   | Homework assignments (group-based) |        15% |
   | Weekly Quizzes (individual)        |        40% |
   | Final exam (individual)            |        30% |

*** Scale
    
    |----+---------+---+--------+----+--------|
    | A+ | \ge 97%   | A | \ge 93% | A- | >= 90% |
    | B+ | \ge 87%  | B | \ge 83% | B- | \ge 80% |
    | C  | \ge 70%  | D | \ge 60% | F  | < 60%  |

   
*** Group Functioning

    Every student needs to be part of a group. I would prefer that groups stay stable throughout the semester, but if there is a good rationale to reconfigure a group or two, we'll do that.

    *Group size*: 2 to 4 students.

    Group creation mechanism: As a default, we'll drop students into groups at random. If you prefer a different group, during the first week you will have the option to re-group. If your group dwindles to just yourself, you'll need to join another group.

    During the final exam, each individual will provide an assessment of the rest of their group. This assessment will determine the "Group Functioning" part of the grade.

    Groups can communicate internally through any mechanism they choose: in-person, zoom, discord, google docs, etc.

*** Reading Reflections

    Each week, each group must complete a "reading reflection" the day *before* class. (That means midnight Sunday, in the case of this class, since class meetings are Monday afternoon.) I will review these assessments before class and use them to tune the in-class activities. Reading reflections are linked from the course schedule and must be turned in on BB. These reflections are part of the learning process rather than the assessment process. That is, they don't assess whether you have achieved mastery of the new material, rather they check whether you have done the necessary preparation.

    *Important*:
    - There are no make-ups.
    - Only one submission per *group*. Everyone in the group gets the same credit.

*** Homework Assignments

    There are weekly *group* homework assighments. I post homework assignments on the class [[./schedule.html][schedule web site]]. Your group will submit assignments via BB.

    Because of the way in which this class is taught, it is important to stay on pace. Homeworks are due *before class*. Late submissions are not accepted except in truly exceptional circumstances.

    *Important*: 
    - Each group should be prepared to present their homework solution in class.
    - *Statement of who did what*. Homeworks are group exercises. Each submission must contain a specific statement of who did what.

*** Weekly Quizzes
    - Each quiz happens during the last 15-20 minutes of class.
#    - "Quiz Guides" posted to the course schedule tell you what to expect on the quiz. Often, they will be closely related to the prior week's homework.

    *Make-up Policy*
    - All quizzes count towards the final grade. Each quiz is scored on a 10 point scale. Missed quizzes score 0/10. Students who miss a quiz or perform badly on a quiz may choose to take the "make-up".
    - The maximum possible score on the make-up is 8/10. (Example: your quiz grade is 5/10. You take the make-up and correctly answer 9 of 10 equally weighted questions. Your final score improves from 5/10 to 8/10.)
    - If you attempt the make-up, that score counts, no matter what your score was on the quiz. (Example: your quiz grade is 7/10. You take the make-up and correctly answer 5 of 10 equally weighted questions. Your final score declines from 7/10 to 5/10.)
    - Scheduling: the GTA will offer the make-up during TA office hours. The make-up can be different than the quiz given in class, but focuses on the same topics.
    - The make-up must be taken promptly and within a window of two class meetings from the quiz. (Example: Quiz 1 takes place on Wednesday, September 1. The make-up must be taken on or before Wednesday, September 15. Another Example: Quiz 11 takes place on Wednesday, November 11. Because we don't meet the week of Thanksgiving, the make-up must be taken on or before Wednesday, December 1.)
    - Each quiz only has one make-up, and you can only attempt that make-up once. However, you are free to use the make-up mechanism on as many different quizzes as you wish.
    - Quizzes are generally returned one week after the quiz is taken. Make-ups are returned after the window has closed.

*** Final Exam

    There will be an final exam at the time specified by the university's final exam schedule.
    -----

** Class Attendance

   I place great emphasis on peer learning and interactive engagement. The class is structured to leverage group interactions to the largest extent possible for the purpose of maximizing learning gain through out the semester.

   Bottome line: It's important to be in class.

** In-Class Exercises

   I plan an in-class exercise for every class. Students will work in their designated group. Some of these exercises need a Java development environment. Very often, the in-class exercises will be closely related to an upcoming homework assignment.

** Record Keeping

   We'll use Blackboard to maintain *RAW* scores and attendance data. Grades are computed according to this syllabus.

   It's the student's responsibility to ensure that Blackboard records are correct. (I'm happy to correct errors.)

   # ** Piazza

   #   I find anonymous discussions unhelpful in this class; here learning is predicated on interactions. Plus, part of your education is to learn to stand behind your questions and ideas. That's how employees function in the working world. Piazza allows partial, but not complete, control of anonymous posts. Should someone post anonymously, I will ask the poster to change the visibility and ask the class not to respond to the anonymous version.


   -----

** Honor Code

   As with all GMU courses, SWE 619 is governed by the [[http://oai.gmu.edu/the-mason-honor-code/][GMU Honor Code]]. In this course, quizzes and the final exam carry with them an implicit statement that it is the sole work of the author.

** Learning Disabilities

   Students with learning disabilities (or other conditions documented with GMU Office of Disability Services) who need academic accommodations should see me and contact the [[http://ods.gmu.edu/][Disability Resource Center]] (DRC) at (703)993-2474. I am more than happy to assist you, but all academic accommodations must be arranged through the DRC.

   -----
** Acknowledgement
   This class is heavily modeled after [[https://cs.gmu.edu/~pammann/][Paul Ammann]]'s [[https://cs.gmu.edu/~pammann/619.html][SWE619 course]].

  
