#+TITLE: SWE 619 Assignment 9

#+HTML_HEAD: <link rel="stylesheet" href="https://nguyenthanhvuh.github.io/files/org.css">

* Goals: =Object= class contracts.

  As it happens, Liskov's implementation of =clone()= for the =IntSet= class (see figure 5.10, page 97) is wrong.

  1. Use the [[./files/IntSet.java][version]] of =IntSet= from the in-class exercise. Implement a subtype of =IntSet= to demonstrate the problem. Your solution should include appropiate executable code in the form of JUnit tests.
  1. Provide a correct implementation of =clone()= for =IntSet=. Again, give appropriate JUnit tests.
  1. Correctly override =hashCode()= and =equals()=. As discussed in the class exercise, the standard recipe is not appropriate in this (unusual) case.
  
* Grading Criteria
  In addititon to code and tests, your deliverable is a story. Explain what is going on at each stage of the exercise. The GTA will primarily grade your story.


* Links
  - [[./index.html][Syllabus]]
  - [[./schedule.html][Schedule]]

