#+TITLE: SWE 619 Assignment 1 

#+HTML_HEAD: <link rel="stylesheet" href="https://nguyenthanhvuh.github.io/files/org.css">
#+HTML_HEAD: <link rel="stylesheet" href="files/org.css">

* Goals
- Getting started on Piazza.
- Getting your group together. 

There are two parts to this assignment:

- Post a brief intro about yourself on the course Piazza page. For any credit, the posting must:
  - be a follow-up to my introduction. In other words, all intros need to be in the same thread.
  - Include a photo appropriate in size, content, and orientation. 
- Your *group* should communicate the composition of your group to me (and the GTA) on Piazza. If you group is sticking with the random assignment, just confirm that. If you have a new group, tell us the composition, and we'll edit the post to reflect the change. 


* Grading Criteria
- Your individual Piazza post adhers to my instructions. (That is, no sideways pictures, no oversize pictures, etc.)
- You are in a group.



* Links
  - [[./index.html][Syllabus]]
  - [[./schedule.html][Schedule]]

