#+TITLE: SWE 619 Assignment 4 

#+HTML_HEAD: <link rel="stylesheet" href="https://nguyenthanhvuh.github.io/files/org.css">

* Goals: Rep-Invariants, contracts, tests
  
  Revisit the mutable Poly example from [[./assign03.html][assignment 3]]. That is, use the one based on a map, not an array.
  
  1. Implement =repOk()=.
  1. Introduce a fault (i.e. "bug") that breaks the rep-invariant. Try to do this with a small (conceptual) change to the code. Show that the rep-invariant is broken with a JUnit test.
  1. Analyzed your bug with respect to the various contracts/methods in Poly. Are all/some/none of the contracts violated?
  1. Do you think your fault is realistic? Why or why not?

  As in assignment 3, your deliverable is a *story*, with exactly the same rationale. Take screenshots (e.g. of failing JUnit tests) as necessary to make your case.

* Grading Criteria
  
  - Correctness of solution
  - Clarity of story
Note: If your group had trouble with the previous assignment, feel free to appeal to your classmates to post a sample solution on Piazza.


* Links
  - [[./index.html][Syllabus]]
  - [[./schedule.html][Schedule]]

