<2022-02-28 Mon>

HW
#+begin_src 
//{N>=0}   # P

// 0<=N  WP
i = 0;
while(i < N){
  i = i + 1;
}
//{i == N}   #Q
#+end_src

- loop invariant: i<=N
WP(S, Q) =
WP([i = 0, while(i<N){i = i + 1}], i == N)
WP([i=0], WP(while(i<N){i = i + 1}, i == N))


WP(while(i<N){i = i + 1}, i == N) =
I & (I & i < N => wp(i=i+1, I)) & (I & i >= N => i == N)

// I
i <= N

// (I & i < N => wp(i=i+1, I))
(i<=N & i < N) => wp(i=i+1, i<=N) =
(i<=N & i < N) => i+1 <= N
 i < N         =>  i <= N-1
 i < N         =>  i < N
   TRUE

// (I & i >= N => i == N)
(i<=N & i >= N) => i == N
 i == N         => i == N
 TRUE

i <= N & TRUE & TRUE  =  i <= N

WP(while(i<N){i = i + 1}, i == N) =  i <= N

WP(i:=0, i<=N) = 0 <= N

VC:
N>=0   =>   0 <= N
TRUE (valid),  program is correct wrt to given P and Q; i <= N

if precondition is given as N >= 5
N >= 5   =>  0 <= N
N >= 5   =>   N >= 0  (valid)

if precondition is given as N >= -5
N >= -5   =>  0 <= N
invalid, cex = N = -4

N=-1

i=0
N=-1



verification vs testing
verification (Hoare logic, abstract interpretation):  is to prove if a program is correct

testing :  is to prove that a program has a bug

Disjkstra:  testing is to prove the presence of a bug, not its absence

Linus Torvalds

Liskov 5.5-5.10
REasoning about correctness in Object oriented programming is even harder

Abstract Function (AF)
- toString(): {1,5,10}

[1,5,10].toString() => {1,5,10}
[5,1,10].toString() => {1,5,10}
[1,5,1,10].toString() => {1,5,10}

Representative Invariant (RepInv)
-
- Binary Tree:
   - exact 2 children
   - null or exactly 2 children
   - 

- Binary Search Tree
   - values of the nodes in the right part of a tree are >= the values of the nodes in the left part of the tree


BT_removenode(BT t, Node n){
  //repr1 :  each node has 2 children
  //repr1 holds on BT

  // code to traverse t, find n, and remove n
  ...

  //ensure that the result preserves the repr inv (repr1)
}

induction (repr/loop) invariant

toString:  abstract function
bool repOK() :   check if the data satisfies the repr invs

IntSet
public boolean repOK(){
  if (els == null) return False;
  //no duplicate check
  ...
}

modular analysis
M1, M2, M3, M4  ....

M1: satisfies its specification(pre/postconditions, repr)
M2: satisfies its specification(pre/postconditions, repr)

In class exercise 5B

#+begin_src java
                     public class Members {
                         // Members is a mutable record of organization membership
                         // AF: Collect the list as a set

                         // rep-inv1: members != null
                         // rep-inv2: members != null && no duplicates in members

                         // for simplicity, assume null can be a member...

                         List<Person> members;   // the representation

                         //  Post: person becomes a member
                         public void join (Person person) {

                             if(!members.contains(person)){
    members.add(person);
  }
                         }

                         //  Post: person is no longer a member
                         public void leave(Person person) {
          members.remove(person);
                         }

#+end_src 
  
repr1  members != null

join: OK,  satisfy contract  
leave: OK,  satisfy contract

repr2 members != null && members cannot have dups

join: NO,  satisfy contract
leave: YES, satisfy contract



* <2022-02-14 Mon>  <2022-02-21 Mon>

Hoare Tripple
{P} S {Q}
{P} : precondition  (e.g.,  0 < x < 5)
{Q} : postcondition  (e.g.,  output = x * 2)
S   : your program (a list of statements)  (e.g., [int y = x * 2; return y;])

Goal: verify that executing S under the assumption that P holds will result in Q (satisfies Q).

If this goal is met, then S is correct wrt to P and Q.

*Partial correctness*:  also assuming that S will terminate  **
Total correctness: does not make the assumption that S will terminate (halting problem)

:= assignment
= , ==  :  equal sign

{True} x := 5 {x==5 or x== 6 or x > 6}  ... valid
{True} x := 5 {x>1}  ... valid
{True} x := 5 {x==5}  ... valid  (preferred, strongest postcondition)

{True} x := 5 {x>5}  ... invalid ,  S is INCORRECT wrt P and Q.

{x = 1 & y = 2} z:= x/y  {z < 1}  .. valid
{x = 2 & y = 4} z:= x/y  {z < 1}  .. valid
{0 < x < y & y  != 0 } z:= x/y  {z < 1}  .. valid    (preferred, weakest precondition)
{0 < x < y } z:= x/y  {z < 1}  .. valid  (preferred, weakest precondition)

{x < y} z:= x/y  {z < 1} *Invalid tripple* , counterexample input x=-1, y = 0
{x = 0 } z:= x/y  {z < 1} *Invalid tripple* , counterexample input x=0, y = 0
{y != 0} z:= x/y  {z < 1} *Invalid tripple* , counterexample x=2, y=1
{x <y & y != 0} z:= x/y  {z < 1} *Invalid tripple* , counterexample y=-1, x = -5


To prove {P} S {Q} is valid, we check if ~P => WP(S, Q)~    
- WP: a function returning the weakest precondition allowing the execution of S to achieve Q
-  WP({x:=x+1}, x=5) = x=4
-  WP({x:=x+1}, x<5)
     =   x < 4  *weakest precondition*
     =   x < 0          -
     =   x < -100

- *Assignment*
- WP(x:= E, Q)  =  Q[x/E]
  WP(x:=3, {x+y = 10})  =   {3+y=10  ->   y = 7]
   WP({x:=x+1}, {x<5}) =   {x+1<5 ->  x < 4} 

- *List of statements*
- WP([S1; S2; S3, ...], Q) = WP(S1, WP([S2; S3; ...], Q))
WP([x:=x+1, y=y*x], {y==2*z}) =
   WP(x:=x+1,WP(y=y*x, {y==2*z})) = 
   WP(x:=x+1, {y*x=2*z}) = 
   {y*(x+1)==2*z}
     
- *Condition*
- WP(if b then S1 else S2, {Q})  =
    b => WP(S1,Q)  &&  !b => WP(S2, Q)

WP(if x > 0 then y :=x  else y:= 0,  {y > 0}) =
x > 0  => WP(y:=x, y>0)  &&  x<=0 => WP(y:=0, y>0)
x > 0  => x>0            &&  x<=0 => 0 > 0
  True                   &&  x<=0  => False
  True                   &&  !(x<=0)
                    !(x<=0) 

{x > 0} if x > 0 then y :=x  else y:= 0  {y > 0}


| x | y | x && y | x OR y | !x | !x OR y |              |
|   |   |        |        |    |         |              |
|---+---+--------+--------+----+---------+--------------|
| T | T | T      | T      | F  | T       | (F or T = T) |
| T | F | F      | T      | F  | F       | (F OR F = F) |
| F | T | F      | T      | T  | T       | (T or T = T) |
| F | F | F      | F      | T  | T       | (T or F = T) |


         
- *Loop*
  - User *has to* provide Loop invariants to compute WP of loop
  - Loop invariant I: captures the meaning of the loop (manually provided by you)
    - property that holds when the loop entered
    - is preserved after the loop body is executed (inductive loop invariant)

WP(while [I] b do S, {Q}) =
   I && (I && b => WP(S,I) && (I && !b)  => Q)

#+begin_src python
  {N >= 0}   // precondition
  i := 0
  while (i < N)
     i := N
  {i == N} // postcondition   
#+end_src

  
- True / 0 >= 0 // LOOP INV
- N >= i  LOOP INV
- N >= 0  LOOP INV
- i >= 0  LOOP INV
- N >= i && N >= 0 && i >= 0

  
- N >= 1  X  cex: N = 0
- N > i    X cex: N =0


I: N >= i
WP({i := 0; while[i<=N] i < N do i:= N}, {i == N})
WP({i := 0}; WP(while[i<=N] i < N do i:= N}, {i == N}))


WP(while[i<=N] i < N do i:=N, {i == N}) =
// WP(while[i<=N] i < N do i:=N, {i == N}) 
  I && (I && b => WP(S,I) && (I && !b)  => Q)

1.  i <= N

&&

2.   (i<= N && i< N) => WP(i:=N, {i<=N})
     (i<= N && i< N) => N <= N
         i<N          =>  TRUE
             TRUE
&&

3.   (i<= N && !(i < N))  => i == N
     (i <=N  && i>=N)     => i == N
        i = N    =>  i = N
        TRUE

i <= N && TRUE && TRUE = i<=N

WP({i := 0}; WP(while[i<=N] i < N do i:= N}, {i == N}))
WP({i := 0}; i<=N)
=  0 <= N

N >= 0 =>  0<=N   .. YES

{N >= -5}  i:=0 ; while (i<N) i:=N  {i=N}
WP(i:=0 ; while (i<N) i:=N,  {i=N})
 0<=N

N>=-5   =>  0<=N

True because (we can use N=-5)   =>   False (b/c 0<=-5 is false)

WP(i:=0; WP(while ..., i=N))
WP(i:=0; i<=N)
0<=N
N>=0  => 0<=N  YES

N>=-5 =>  0<=N  NO


- INVALID HOARE TRIPPLE DOES NOT MEAN THE PROGRAM IS WRONG (i.e., assume pre, execute prog, does not satisfy post)
- VALID HOARE DOES IMPLY THAT THE PROGRAM IS CORRECT



Chosen I = N >= 0

WP(while[N>=0] i < N do i:=N, {i == N}) =
// WP(while[N>=0] i < N do i:=N, {i == N}) 
  I && (I && b => WP(S,I) && (I && !b)  => Q)

1.  N>=0

&&

2.   (N>=0 && i< N) => WP(i:=N, {N>=0})
     (N>=0 && i< N) => i>=0

&&

3.   (N>=0  && !(i < N))  => i == N
     (N>=0  && i>=N)     => i == N
     i >= 0    =>  i == N

1 && 2 && 3
R = N >= 0 && (N >=0 && i < N => i >= 0) && (i >= 0 => i == N)

wp(i:=0, R) =
N >= 0 && (N >=0 && 0 < N => 0 >= 0) && (0 >= 0 => 0 == N)
N >= 0 &&  TRUE  &&  (0 == N)
N >= 0 && (0 == N)
0 == N

N >= 0   =>  0 == N   NO  (cex N = 5)

*

- Loop inv location

  while b {
  //body
  }

  while (1) {
   **[I]**
   if(!b) break
   //body
  }

- simplification
  
  
- insufficiently strong

  I1  i > 0
  I2  N > 0 
  I3  
  I4

  N, i , x


  0 = 0
  
  
- (x < y && y < 10)  =>   x < 101
- x < 100            => x < 101
- x < 100000         =>  x < 101
  

* <2022-02-07 Mon>

  
#+begin_src java
  public static int months (int principal, double rate, int payment){
      // Requires: principal, rate, and payment all positive and payment is sufficiently large to drive the principal to zero.
      // Effects:  return the number of months required to pay off the principal

  }
#+end_src


check vs unchecked exceptions
- Checked exception: exception that should be recoverable (and you should write code (try/catch...) to handle it)
- Unchecked exception: exceptrions that we cannot recover from / fatal errors   


Polynomial
- 10 
- ax + bx + 5
- 10x + 5x^2 - 4

- c_1*x_1^d_1 + c_2*x_2^d_2


- 5x*y  # does not allow in Poly implementation
- cannot have negative degree (allows deg >= 0)
- coefficients are integers

5+3*x^2
Poly(deg=2, trms=[5,3])    5+3*x
Poly(deg=2, trms=[5,0,3])  5+3x^2

Poly(deg=2, trms=[5,0,3,0,0,0,0,0...])  not allowed in Poly implementation

Abstraction
Abstract representation: 5+3*x
Concrete/Internal representation:
Poly(deg=2, trms=[5,0,3],
Poly(deg=2, trms=[5,0,3,0,0,0,0,0...]))

toString()

#+begin_src java
  public class Poly {
      private int[] trms;
      private int deg;

      // Effects: Initializes this to be the zero polynomial
      public Poly() {
         trms = new int[1]; trms[0] = 0;
         deg = 0;
      }

      // Effects: If n < 0 throws IllegalArgumentException
      // else initializes this to be the polynomial c*x^n
      public Poly(int c, int n) throws IllegalArgumentException {
         if (n < 0) {
            throw new IllegalArgumentException("Poly(int, int) constructor");
         }
         if (c == 0) {
            trms = new int[1]; trms[0] = 0;
            deg = 0;
            return;
         }
         trms = new int[n+1];
         for (int i=0; i < n; i++) {
            trms[i] = 0;
         }
         trms[n] = c;
         deg = n;
      }

      private Poly (int n) {
         trms = new int[n+1];
         deg = n;
      }

      // Effects: returns the degree of this
      public int degree() {
         return deg;
      }

      // Effects: returns the coefficent of the term of this whose exponent is d
      public int coeff_book(int d){
          if (d < 0 || d > deg) return 0 else return terms[d];
      }
    
      // @throws IAE if d < 0
      // Effects: returns the coefficent of the term of this whose exponent is d
      public int coeff(int d) {
         if (d < 0) throw new IAE();
         return (d > deg) ? 0 : trms[d];
      }

      // Effects: If q is null throw NullPointerException
      // else return the Poly this - q
      public Poly sub(Poly q) throws NullPointerException {
         return add(q.minus());
      }

      // Effects: return the Poly -this
      public Poly minus() {
         Poly r = new Poly(deg);
         for (int i=0; i <= deg; i++) {
            r.trms[i] = -trms[i];
         }
         return r;
      }

      // Effects: If q is null throw NullPointerException
      // else return the Poly this + q
      public Poly add(Poly q) {
         Poly la, sm;
         if (deg > q.deg) {
            la = this; sm = q;
         }
         else {
            la = q; sm = this;
         }
         int newdeg = la.deg;
         if (deg == q.deg) {
            for (int k = deg; k > 0; k--) {
               if (trms[k] + q.trms[k] != 0) {
                  break;
               }
               else {
                  newdeg--;
               }
            }
         }
         Poly r = new Poly(newdeg);
         int i;
         for (i = 0; i <= sm.deg && i <= newdeg; i++) {
             r.trms[i] = sm.trms[i] + la.trms[i];
         }
         for (int j = i; j <= newdeg; j++) {
            r.trms[j] = la.trms[j];
         }
         return r;
      }

      // Effects: If q is null throw NullPointerException
      // else return the Poly this * q
      public Poly mul(Poly q) throws NullPointerException {

         if ((q.deg == 0 && q.trms[0] == 0) || (deg == 0 && trms[0] == 0)) {
            return new Poly();
         }

         Poly r = new Poly(deg + q.deg);
         r.trms[deg + q.deg] = 0;
         for (int i = 0; i <= deg; i++) {
            for (int j = 0; j <= q.deg; j++) {
               r.trms[i+j] += trms[i]*q.trms[j];
            }
         }
         return r;
      }

      public String toString() {
         String r = "Poly:";

         if (deg == 0 || trms[0] != 0) {
             r += " " + trms[0];
         }

         for (int i = 1; i <= deg; i++) {
            if (trms[i] < 0) {
               r += " - " + -trms[i] + "x^" + i;
            }
            else if (trms[i] > 0) {
               r += " + " +  trms[i] + "x^" + i;
            }
         }
         return r;
      }
  }
#+end_src


q = [1,2,3]
q' = q.enQueue(4)
q' = [1,2,3,4]   Queue.elements=[1,2,3,4] , Queue.size=4
q = [1,2,3]

q = [1,2,3]
e = q.peek(); //e = 1
q' = q.deQueue();
q' = [2,3] 


---
Hoare Logic
- Automatic way to *verify* that an implementation satisfies a given specification (pre/post conditions)
- Imperative programs (the version I am showing you does not deal with advanced OO concepts, no inheritence, no pointers/references)
- 


Hoare Tripple
{P} S {Q}
{P} : precondition  (e.g.,  0 < x < 5)
{Q} : postcondition  (e.g.,  output = x * 2)
S   : your program (a list of statements)  (e.g., [int y = x * 2; return y;])

Goal: verify that executing S under the assumption that P holds will result in Q (satisfies Q).

If this goal is met, then S is correct wrt to P and Q.

*Partial correctness*:  also assuming that S will terminate  **
Total correctness: does not make the assumption that S will terminate (halting problem)

:= assignment


{True} x := 5 {x==5 or x== 6 or x > 6}  ... valid
{True} x := 5 {x>1}  ... valid
{True} x := 5 {x==5}  ... valid  (preferred, strongest)

{True} x := 5 {x>5}  ... invalid ,  S is INCORRECT wrt P and Q.


* <2022-01-31 Mon>

- Specification/Contract of a program

  #+begin_src java
    int add2numbers(int x, int y){
        //requires/preconditions
        //- x and y are integers

        //effects/postconditions
        //- z is integer
        //- z = x + y
        return z;
    }
  #+end_src

  #+begin_src

    List sortAscending(List<Int> l){
       //preconds:  l is a list of integers 
       //l cannot be null
       //l cannot contain null

       //postconditions:
       - l' has an ascending order 
       - l' is a permutation of l
       return l';
    }
  #+end_src


#+begin_src java
  User u = new User(“SWE619”);
  u.equals(u); // contract: T, impl: T
  u.equals(null); //contract: F, impl: F
  u.equals("SWE619"); //contract: F, impl: F

  User v = new User(null);
  v.equals(u); //contract:F, impl: F
  u.equals(v); //contract:F, impl: exception
  
#+end_src


testing vs verfication
- testing:  test if the program works over a *finite* number of inputs
- verification: formally/mathematically show/guarantee that a program works over *all possible* inputs
  - Nasa rovers
  - A318: formally proved that no floating pt errs
  - robotic surgical arms



Precondition (P):
  - client/customer: establish  P
Postcondition (Q)
  - developer/implementation:  establish Q under assumption that P is established


- If a program is not correct
  - if precondition is wrong: blame client
  - if (precondition is met) postcondition is wrong: blame developer


- sqrt example  :  y = sqrt(x)
  preconditions:
  - x > 0 (preferred)
  - x >= 0 (preferred)
  - x is an integer (preferred)
  - 100 <= x  <= 200  (not preferred)
  - x = 101  (not preferred)

  - best precondition: no precondition
  
  postconditions:
  - y is a number
  - y <= x
  - y*y == x (-/+ epsilon)   ~~ y = x/y  (preferred)



- partial vs total specification
  - partial specification:  has a precondition
  - total specification:  has NO precondition

- how to turn a partial into a total specification?
  //partial spec
  sqrt(x):
     precondition: x >= 0
     postcondition:  y*y == x (-/+ epsilon)

  //total spec
  sqrt(x):
     precondition: 
     postcondition:
         //if x < 0:  raise exception
         //ow.  y*y == x (-/+ epsilon)

  //div_xy(x,y):   output = x/y
  partial spec:
   precond:  y != 0
   post :   y*output == x

  total spec:
    precond: true
    postcondition:   if y is 0, raise exception(DivByZero);
    y*output = 



list = null,  NPE
list = [], IOBE
list = [1], []  *
list = [1,2,3] , [2,3] *

pre: non-empty list and non-null
post: remove the head, return the rest (tail)

//total
pre: 
post:
if  (list is []) throw IOBE
if (list is null) throw NPE
remove the head, return the rest (tail)

specification too specific to implentation (remove(0)), to fix: throws IAE instead of IOBE when list is []

* <2022-01-24 Mon>

What does it mean to write correct software?
- It conforms to some expectation (software contracts or specificaions)
- Should pass its testsuite  ..
- Should not have exception or performance issues


- Specifications/contracts (requirements)
- Should not have exception or error

- Performance, maintainable, expandable :  desired qualities , but not
required for *correctness*


f (x, y):   // return output = x  / y
   //precond:  x,y are reals

  if y == 0:  raise exception
  ...



preconditions
- x,y are reals
- y != 0
- x >= 0
- x >=  100
- we want preconditions are are as WEAK as possible
   1. x could be any real numbers
   2. x must be non-negative
   3. x must be >= 100

3 is stronger than 2 is stronger 1
the best precondition is the weakest one, i.e., TRUE  (the function
has no assumption on the input)


- output : number
- output ~   x /y    (output * y   ~= x)

- precondition/requirements:  a condition over the inputs ,
assumptions that we make when the function starts
   - x,y being real numbers
   - y != 0

- postcondition/behaviors:  behavior of the function (the program),
relationshp btw inputs and outputs

   1. output is a number (reals,... )     weaker
   2. output * y ~= x                     stronger

   the best postcondition is the strongest one,  i.e.,   output * y ~= x

- side-effects:
   - can change input X, ....


task: sorting a list of numbers in ascending order  (e.g., 1,5,10,...)

g(l):
  //precondition: a list of numbers
  //same data types (comparable)
  //iterable ...
  //finite

  // l is arraylist of integers
  // precondition over l:   none,  true

   postcondition:
   - |l| == |l'|
   - l' same datatype  as l
   - [1,2,1,2]   [1,1,1,2]
   - l' is a permutation of l
   - l' ascending order


 //sort l in ascending order
 return l'




type checking

- void f (int x, int y){
   int o = 3;
   return o;
}

- type-checker is light-weight analysis and therefore can be built in in comilers,  just check if x and y are integers 
- assertion checking is heavy-weight because we can check expressive properties such as y = x ** 2; never built in, have to do some serious program analysis for this.
assertion(y = x**2);

